### ISSUE TITLE
[Tracking] go-ethereum/1.10.2 merge TODOs and tidbits

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#365]
This issue is tracking checklists and TODOs related to the merge of ethereum/go-ethereum 1.10+ series releases and the associated protocol upgrade features. This release series includes features implemented in the Berlin fork, and proposed for Ethereum Classic's tentative Magneto fork.

### Overview

PRs are stacked.

- `master` <- go-ethereum/1.10.1 https://github.com/etclabscore/core-geth/pull/348
- https://github.com/etclabscore/core-geth/pull/348 <- go-ethereum/1.10.2 https://github.com/etclabscore/core-geth/pull/357

### TODOs

-  [x] `tests/testdata`.  This gets bumped. ethereum/tests has been refilled and now includes something like 150 new tests for Berlin features. I regenerated the tests based on the commit upstream is using.
    - [ ] These generated tests need reviewed. https://github.com/etclabscore/tests/pull/4
        - Read https://github.com/etclabscore/tests/pull/4#issue-607707514. Review footprint, configuration schemas and presence.
        - This is where the state tests are generated: https://github.com/etclabscore/core-geth/blob/merge/foundation-release/1.10.1-resolved/tests/state_mgen_test.go#L204. Please review.
        - This is where the difficulty tests are generated: https://github.com/etclabscore/core-geth/blob/merge/foundation-release/1.10.1-resolved/tests/difficulty_mgen_test.go#L141. Please review.
- [x] @meowsbits `core/blockchain_af_test.go`. I resolved conflicts from the hip there. Review. 
- [x] @meowsbits Make sure header `nil` checks/validations are in place. IIRC core-geth has this and go-ethereum does not. I believe must be in place since I believe there is a miner test testing nil header cases. 
- [x] #354 `panic: invalid number of list elements: 0`
- [x] @ziogaschr Review and handle `X_Override` values (eg. `BerlinOverride` and `--override.berlin`, etc.), eg. w/r/t `SetupGenesisBlockWithOverride` and default config. re #367
- [x] @meowsbits `--debug` is missing. On purpose? :( 
    _It becomes `log.debug`._ See a7443c0e5c for related fixes regarding deprecated `pprof` flags.
- [x] @meowsbits Add core-geth additional chain flags, re https://github.com/etclabscore/core-geth/pull/357#pullrequestreview-635112410. 
    Done with 49bd5e70385382528187bd42365392b4a91fad5f.
- [x] @meowsbits Remove `cmd/echaindb`, per https://github.com/etclabscore/core-geth/pull/357#pullrequestreview-635113268
    - [x] Proposed with PR https://github.com/etclabscore/core-geth/pull/366
- [x] @ziogaschr Set Magneto activation block numbers for classic|mordor|kotti chains #368
- [x] @ziogaschr Fixup/review empty version log, noted in https://github.com/etclabscore/core-geth/pull/348#issuecomment-805988314 #373 

### Testing Checklist

- [ ] Developer sync 
    - [ ] Classic
      - [x] 4e73750 @iquidus
      - [x] 82d0101af5 @meowsbits
      - [x] d8799214 @ziogaschr
    - [ ] Mordor
      - [x] 4e73750 @iquidus
      - [x] d8799214 @ziogaschr
    - [ ] Kotti
      - [x] 4e73750 @iquidus
      - [x] d8799214 @ziogaschr 
    - [ ] Ropsten
    - [ ] ETH
- [x] Must pass: Condensed regression tests
- [ ] Must pass: Uncondensed regression tests (via Jenkins)
- [ ] Extrapolated ethereum/tests suite.
    - [x] Must pass
    - [x] Tests reviewed

**Comment by iquidus** [comment]
- [ ] Classic
  - [x] 4e73750 @iquidus
- [ ] Mordor
  - [x] 4e73750 @iquidus

**Comment by iquidus** [comment]
- [ ] Kotti
  - [x] 4e73750 @iquidus

**Comment by ziogaschr** [comment]
- [ ] Mordor
  - [x] d8799214 @ziogaschr 
- [ ] Kotti
  - [x] d8799214 @ziogaschr

**Comment by meowsbits** [comment]
I'm running a `--syncmode=snap` Classic node at `"enode://ce7cbef463c5bac7e310a1ad2279975d8a5b38627f462cd6157a8bd310641ae9e33aae7634afc8b102be864491cba8dd33c9343b94674ba86be8afc74f4721a9@159.203.56.33:30369"`. 

This node should be available indefinitely. I'll restart it when upgrading to the forthcoming next release, but should be stable between and after that.

On `ethstats` as `meowsbits-classic-dev-fun`. Developer metrics as `host=isaac-rottor-fun`. 

```
# ./build/bin/geth version
CoreGeth
Version: 1.11.23-unstable
Git Commit: faf705db58145f9ea61af6caab9041e0237aeefc
Git Commit Date: 20210504
Architecture: amd64
Go Version: go1.15.5
Operating System: linux
GOPATH=/root/go
GOROOT=/root/go1.15.5.linux-amd64

```

**Comment by ziogaschr** [comment]
An RC release is being prepared [here](https://github.com/etclabscore/core-geth/releases/tag/untagged-84856fcb988a1cc88954)

**Comment by meowsbits** [comment]
Great stuff guys, thanks for this. Closing, since `v1.12.0-rc1` has been released.
